### ISSUE TITLE
using $ionicModal.fromTemplateUrl() instead of .fromTemplate()

### ISSUE THREAD

**Issue by lamson** [JrSchild/jr-crop#10]
Hi, just wondering if this is a bug or I've got something wrong here. Basically I wanted to modify the modal crop template html more easily. So I uses $ionicModal.fromTemplateUrl() instead. This function returns a promise with a modal instance, unlike .fromTemplate() which returns the modal instance.
Here are my changes:

          crop: function (options) {
            this.initOptions(options);

            var cropScope = $rootScope.$new(true);

            ionic.Utils.extend(cropScope, this.options);

            $ionicModal.fromTemplateUrl('templates/modals/modal-crop.html', {
              scope: cropScope
            }).then(function (modal) {

              cropScope.modal = modal;
              // Show modal and initialize cropper.
              return cropScope.modal.show().then(function () {
                return (new jrCropController(cropScope)).promise.promise;
              });
            });
          },

This popups a crop modal with my template just fine. However, when I click 'Crop' the promise doesn't resolve(canvas) correctly. It did create a canvas, called .resolve(canvas), but .then(function(canvas) {}) doesn't work some how.

Do you have any ideas?

**Comment by JrSchild** [comment]
Hey lamson,

You're almost there. All you need to do is return the result of the chained promise of $ionicModal. Like this:

```
return $ionicModal.fromTemplateUrl('templates/modals/modal-crop.html, {
...
```
That will make sure a promise is returned after the template has been loaded. Let me know if this worked for you.

**Comment by lamson** [comment]
It works perfectly! I'm all new to JS and all these promises... 
Thank you so much!
