### ISSUE TITLE
use interpolateProvider

### ISSUE THREAD

**Issue by benallfree** [JrSchild/jr-crop#27]
Could I make a suggestion to use angular's `$interpolateProvider` instead of assuming `{{ }}` for templates?

```
.factory('$jrCrop', [
  '$ionicModal',
  '$rootScope',
  '$q',
  '$interpolate',
function($ionicModal, $rootScope, $q, $interpolateProvider) {
  function i(expr)
  {
    return $interpolateProvider.startSymbol() + expr + $interpolateProvider.endSymbol();
  }
  var template = '<div class="jr-crop modal">' +
                    '<div class="jr-crop-center-container">' +
                      '<div class="jr-crop-img" ng-style="{width: width + \'px\', height: height + \'px\'}"></div>' +
                    '</div>' +
                    '<div class="jr-crop-center-container">' +
                      '<div class="jr-crop-select" ng-class="{\'jr-crop-select-circle\': circle}" style="overflow: hidden" ng-style="{width: width + \'px\', height: height + \'px\'}"></div>' +
                    '</div>' +
                    '<div class="bar bar-footer bar-dark jr-crop-footer">' +
                      '<button class="button button-clear" ng-click="cancel()">'+i('cancelText')+'</button>' +
                      '<div class="title">'+i('title')+'</div>' +
                      '<button class="button button-clear" ng-click="crop()">'+i('chooseText')+'</button>' +
                    '</div>' +
                  '</div>';
```

**Comment by JrSchild** [comment]
Hi @benallfree,

Seems like it's adding extra complexity. What are the pros and cons of this? Also note that you can overwrite the (default) template yourself.

**Comment by benallfree** [comment]
Hi, well I noticed the problem because I have an Angular app configured to use `<% %>` instead of `{{ }}` due to syntax collisions with a HAML parser.

My proposed change would make js-crop compatible with all Angular configurations. Otherwise someone has to dig through the js-crop source code like I did to figure out why it's not working :)

But yes this could also easily be solved by creating a custom template *if* you knew that's why it wasn't working. Maybe a note in the readme would be fine too.

Thanks for your work on js-crop, it's a great tool.

**Comment by JrSchild** [comment]
Thank you for your feedback.

I agree with you. This should be beter documented. I will make sure to update the docs with explanation and examples soon. It can probably be done in a simple and efficient way.

*~~js-crop~~ jr-crop  ;)

**Comment by JrSchild** [comment]
For now you can likely do this to make it work.

```
$jrCrop.defaultValues.template = $jrCrop.defaultValues.template
    .replace(/{{/g, '<%')
    .replace(/}}/g, '%>');
```

**Comment by benallfree** [comment]
Ah good idea!

**Comment by JrSchild** [comment]
Can you confirm that this indeed works and that the updated REAMDE is clear?
