### ISSUE TITLE
How do I crop a full-hd image to a resolution that doesn’t fit on the device?

### ISSUE THREAD

**Issue by 0x1ad2** [JrSchild/jr-crop#28]
At first sorry for my vague question I'm going to make it more clear.

The final result I want to achieve is sharing (using ngCordova social sharing plugin) an image that has a resolution of 851 x 315 (facebook cover image).
- I shoot a photo through my Samsung Galaxy S4 (the resolution of the image is/will be 1080 x 1920)

<img src="https://forum.ionicframework.com/uploads/default/original/3X/a/8/a8ad599745b26359ab731f14be7827554fa9b90a.jpg" width="375" height="500">
- I accept the image as you need to do that on android (the resolution of the image still is 1080 x 1920)

<img src="https://forum.ionicframework.com/uploads/default/original/3X/c/6/c6b52242f0a70d65921e6c521b5fe21e678c6a6f.jpg" width="375" height="500">
- I open up the cropper (currently using https://github.com/JrSchild/jr-crop) 
  I set the options to be 851 x 315

<img src="https://forum.ionicframework.com/uploads/default/original/3X/9/c/9cbef1b426d6bdcda73dfc8c499ae97dce8fbb0c.jpg" width="375" height="500">

The cropper doesn't have the set dimensions because it can't, because the device resolution is too small.
How could I crop a full-hd picture crop it to 851 x 315 and still be able to work with the picture.

To show what the desired result will be I tried the same in Twitter (for iPhone tough), here I'm going to set the image as a new header image that's (1500 x 500).

<img src="https://forum.ionicframework.com/uploads/default/original/3X/e/6/e62d853b5b624a0631a0de36da0f78395a5464c2.jpg" width="281" height="499">

**Comment by asturur** [comment]
I was checking here
https://github.com/JrSchild/jr-crop/blob/master/dist/jr-crop.js#L76

``` javascript
        if (selectAspectRatio > imgAspectRatio) {
          this.scale = this.last_scale = this.options.width / this.imgWidth;
        } else {
          this.scale = this.last_scale = this.options.height / this.imgHeight;
        }
```

Probably the image is 1080x1920 with the exif rotation flag for the phone orientation.

In your case it may be ( i'm completley noob about both this scaler and ionic framework ) that swapping this if condition would help you. scaling by height will make your picture looks ok on the cropper.

I think that when the image have different orientation other than the screen, you should add some additional check:

``` javascript

        isOrientationSame = ((selectAspectRatio >= 1 && imgAspectRatio >=1) || (selectAspectRatio < 1 && imgAspectRatio <1));

        if (selectAspectRatio > imgAspectRatio) {
          if (isOrientationSame) {
            this.scale = this.last_scale = this.options.width / this.imgWidth;
          } else {
            this.scale = this.last_scale = this.options.height / this.imgHeight;
          }
        } else {
          if (isOrientationSame) {
            this.scale = this.last_scale = this.options.height / this.imgHeight;
          } else {
            this.scale = this.last_scale = this.options.width / this.imgWidth;
          }
        }
```

I have no chance or time to check if this works. But i think is a quick try for you or at least a hint for the good direction.

**Comment by JrSchild** [comment]
Hi Dennis,

I am aware of this situation and the way this could be handled definitely needs to improve. It's too vague right now and was initially only meant for square images. To answer your question in #24, yes this is part of the roadmap.

What I think you could do for now is scale down the proportions (851 x 315) down to the screensize. So manually retrieve the screenwidth and scale them down.

Let's say the `screenwidth = 320` you would end up doing:
`height = (851 / screenwidth) * 315 = 118`

If you set `width: 320` and `height: 118` it might just work.

**Comment by asturur** [comment]
Ok @0x1ad2 i just tried :)

**Comment by 0x1ad2** [comment]
@asturur thanks for looking into it, I've tried to used the screen orientation check and just simple reversing the current statement but both doesn't seem to work.

@JrSchild thanks for the confirmation and explanation why it's not build in on default. I could scale down the proportions (I currently do) but after cropping the image is put on canvas, edited and exported so If I put in on a 320 x 118 canvas it will export as 320 x 118 not as 851 x 315.

Do you guys know any other good crop plugin that has the ability to deal with the aspect ratio.

**Comment by JrSchild** [comment]
@0x1ad2 Did you try it out? I'm 99% sure it won't ;). It will export the image in the highest possible resolution.

**Comment by 0x1ad2** [comment]
@JrSchild I've been working on the app for a couple of weeks now so yeah of course I did try it out ;)
here's a code snipped from my code base, don't mind the options (I've used @akreienbring his PR-code).

``` javascript
     $jrCrop.crop({
            url: "data:image/jpeg;base64," + imageData,
            width: canvasWidth,
            title: '',
            cancelText: 'Annuleren',
            chooseText: 'Uitsnijden',
            allowRotation: true,
            buttonLocation: 'header',
        }).then(function (canvas) {
            $rootScope.latestShot = canvas.toDataURL();
            $state.go('tab.blur');
        }
```

As  you can see I'm exporting the canvas using the toDataURL method.

**Comment by JrSchild** [comment]
You'll also need to set the height in this case. Just try this with my latest version:

```
options = {
  url: "data:image/jpeg;base64," + imageData,
  width: 320,
  height: 118,
  title: '',
  cancelText: 'Annuleren',
  chooseText: 'Uitsnijden'
}
```

I just tried it out myself. The resolution of the image will be biggest possible within those proportions, that has always been my intention.

**Comment by 0x1ad2** [comment]
It's also not working I removed the height on purpose some seconds ago, forgot to put it back in.
It was 

```
 height: canvasHeight
```

And my dimensions where

```
var canvasWidth = 320;
var canvasHeight = 315;
```

I will use your dimensions and show the result to  you

**Comment by JrSchild** [comment]
In your case you will want to calculate the sizes for your screen:

var width = window.innerWidth \* 0.9; // Add a small margin or something.

options.width = width;
options.height = ~~((851 / width) \* 315)

**Comment by JrSchild** [comment]
My bad, messed up the calculation. Should be this:

```
var width = window.innerWidth * 0.9; // slight margin
$jrCrop.crop({
  url: image,
  width: width,
  height: ~~((width / 851) * 315)
})
```

![ios simulator screen shot 23 dec 2015 16 29 19](https://cloud.githubusercontent.com/assets/451164/11979311/9ef17b8a-a992-11e5-83bc-b570c2ffcb6d.png)

![ios simulator screen shot 23 dec 2015 16 29 31](https://cloud.githubusercontent.com/assets/451164/11979310/9eef2aec-a992-11e5-8721-8bf7e1b2c4a7.png)

![1450884565764](https://cloud.githubusercontent.com/assets/451164/11979352/ede0c656-a992-11e5-9616-23414e70e13b.jpg)

**Comment by 0x1ad2** [comment]
@JrSchild thanks for that I'm going to try it right now, I said "I will use your dimensions and show the result to you" but I can't get the result due to a to long base64 dataURL. Any tips for handling those, what would you advice?

**Comment by JrSchild** [comment]
It's much better to retrieve the url to the file and use that instead of base64 data.

-Edit; Oh you mean for the results. Yes check the examples folder. It uses a .toBlob polyfill, currently from blueimp. There's a branch that shims it internally but I haven't had the chance to test it on Android yet.

If you would like to show the result in the DOM it's best to turn it into a BLOB and then retrieve a [blob URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL).

**Comment by 0x1ad2** [comment]
@JrSchild I tried your code and the cropper is working fine for now.

![](https://i.gyazo.com/17146973d1aa438ddf37c49d7a953e47.png)

It's producing the following image 

![](https://i.gyazo.com/431f36f593b00600ae48eb0e08281ea1.png)

But after that I'm putting it on canvas again for some image manipulation added some background overlays and text objects using Fabric.js.

And if I export it after that I'll end up with this

![](https://i.gyazo.com/fc450835beb02f6244c2aa0454c75ecf.png)
- the only solution I've got in mind is to load the full image and make it horizontal scrollable but that causes laggy/buggy UI

**Comment by JrSchild** [comment]
Okay you're getting there.

So the resulting image of jr-crop will be the maximum possible resolution in those proportions, it could be bigger or smaller than your target size. First of all, scaling this is logic you probably want to do on the server with proper tools like image-magick, or sharp. Browsers are a) not very good at this with quality, b) slow when using other algorithms. I have already experimented with this, resulting in really bad performance.

What I thought of is that because you are cropping an image on a smaller screen, the result can never be exactly 851 x 315 when you scale it down (or up). You might want to round the height up (`height: Math.ceil((width / 851) * 315)`) and then manually scale the image to a width of 851px, then remove the excess pixels by placing it on a canvas of 851 x 315 (or cropping with your much better server-tools).

Your example probably went wrong because you are assuming specific measurements when you place it on another canvas. So if you would really like to do the scaling on the client you should place it with [context.drawImage](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) with `sWidth: 851` and `sHeight: null` (sx and sy are 0 obviously)

-Edit: Excuse me [dWidth and dHeight](http://stackoverflow.com/a/13903654).

Note that when you draw it on another canvas you don't need to get its contents first. Just draw the whole thing. `destinationContext.drawImage(canvas, 0, 0, 851, null);`

**Comment by JrSchild** [comment]
I'm assuming it's fixed. Feel free to comment here if you have further questions regarding your issue.

**Comment by 0x1ad2** [comment]
Ja het is opgelost, bedankt voor je hulp!

2016-01-05 15:49 GMT+01:00 Joram Ruitenschild notifications@github.com:

> I'm assuming it's fixed. Feel free to comment here if you have further
> questions regarding your issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JrSchild/jr-crop/issues/28#issuecomment-169020955.

## 

Met positieve groet,

_Dennis Bruijn_
Full-stack Web Developer

  http://nl.linkedin.com/in/dbbruijn

http://goog_1423228033

**Comment by JrSchild** [comment]
Top! Graag gedaan
