### ISSUE TITLE
Cordova android issue

### ISSUE THREAD

**Issue by cordova-android** [JrSchild/jr-crop#34]
after downloading plugin 
i confused about paths

but i but folders as follows:

jrcrop-->hooks
         --->platforms
         --->plugins
         --->config.xml
         --->www----------->angular (folders include js )
          --->www----------->angular-ui (folders include js )
           --->www----------->css
            --->www----------->images(from plugin)
            --->www----------->ionic (folders include css and js )
            --->www----------->js
            --->www----------->uploads
              --->www----------->app.js
                --->www----------->canvas-to-blob.min.js
             --->www----------->index.html
             --->www----------->jr-crop.js
             --->www----------->jr-crop.css

```
     put the problem is the plugin not work in android emulator
```

**Comment by JrSchild** [comment]
You can put it wherever you want to put it. Most people have a custom build step to build/concat/minify js/css files. If you don't have this, make sure you reference the .js file after your angular/ionic files and css file after the rest of your ionic.css file.

I am not really supporting Android, although I do often hear that it works in recent versions.

**Comment by cordova-android** [comment]
i need to understand your comment in clear
i.e i need more details

**Comment by cordova-android** [comment]
i have in emulator like this

http://s10.postimg.org/wqy4pl89l/image.gif
<a href='http://postimg.org/image/kp2qvfz11/' target='_blank'><img src='http://s10.postimg.org/kp2qvfz11/image.jpg' border='0' alt="1" /></a>

**Comment by JrSchild** [comment]
Looks like your CSS file isn't loaded

**Comment by cordova-android** [comment]
i attached my app and upload it
http://www.megafileupload.com/vzWW/jrcrop.rar

**Comment by cordova-android** [comment]
you have received it?

**Comment by JrSchild** [comment]
I'm at work. Unfortunately I won't be able to help you.

**Comment by cordova-android** [comment]
ok but you have an cordova app work good with jr-crop?

**Comment by JrSchild** [comment]
The examples folder works. You can also try building [this example project](https://github.com/JrSchild/jr-crop-cordova). Haven't tried it in a while so it might be broken.

**Comment by cordova-android** [comment]
but this is no thing to be cropped 
so i can't use jrcrop

**Comment by cordova-android** [comment]
is there any solution for my issue?

**Comment by cordova-android** [comment]
?

**Comment by JrSchild** [comment]
I can't really tell what's wrong. The example folder works as far as I know so it's up to you to merge that into your own project.

**Comment by cordova-android** [comment]
ok but is there retractions needed to work

**Comment by cordova-android** [comment]
ok but is there retractions needed to work
i mean where every folder or js or css need to put in directories or in embed script files in specific hierarchy

**Comment by cordova-android** [comment]
i need folders which is used 
    ionic.css
 canvas-to-blob.min.js
ionic.bundle.js

as there are error occure when i used newest versions

**Comment by JrSchild** [comment]
What do you mean by retractions? Include the css after the ionic css and the js after ionic and angular.
