### ISSUE TITLE
Background color for small image

### ISSUE THREAD

**Issue by MEmmanuel** [JrSchild/jr-crop#43]
When I crop a small image (smaller than target), the image is completed with a black background.
I'd rather customize it to white.
This image shows an example:
![capture d ecran 2016-09-27 a 09 14 33](https://cloud.githubusercontent.com/assets/8722860/18863694/fd2d4720-8492-11e6-94da-3c0ee0beccf7.png)

**Comment by JrSchild** [comment]
You can do this by overwriting jr-crop's classes with your custom css.

**Comment by MEmmanuel** [comment]
o? which class?
Because even if I display crop on a white background, the resulting image still returns with black background like before:
![capture d ecran 2016-09-27 a 09 47 34](https://cloud.githubusercontent.com/assets/8722860/18864608/728f0748-8497-11e6-9cc0-7fc4e8960506.png)
Like if image was autocomplete with black when actually cropped.

**Comment by MEmmanuel** [comment]
I managed to do what I want this way:
I insert this:
`context.fillStyle = '#fff'; context.fillRect(0, 0, canvas.width, canvas.height);`
Just before this:
`context.drawImage(this.imgFull, sourceX, sourceY);`
Line 242 of jr-crop.js

Whit this, it result in what I want:
![capture d ecran 2016-09-27 a 10 08 33](https://cloud.githubusercontent.com/assets/8722860/18865256/8e10b48c-849a-11e6-9013-f78aba24286f.png)

What do you think about this? I supposed it would rather be an option.
