### ISSUE TITLE
Testing in Android

### ISSUE THREAD

**Issue by jjimenezlopez** [JrSchild/jr-crop#9]
Hi, I've just added two pull requests. I'm writting just to let you know that I am testing jr-crop on two devices:

 * Nexus 5 with Android L 5.0.1
 * OnePlus One with CyanogenMod 11 (with Android 4.4.4)

I'm working with ionic and Cordova. In the first case (Nexus 5) jr-crop works ok. In the second case (OnePlus), with the stock WebView the touch events are not working.

But I have migrated my ionic project recently to [Crosswalk](https://crosswalk-project.org/), and jr-crop works like a charm in both cases :+1:

**Comment by JrSchild** [comment]
That is great to hear. I've never had the opportunity to test it on an Android device myself but from what I hear, thing are going pretty okay. I have merged in both of your requests and released jr-crop 0.1.1. I'm curious to see what people build with it. Let me know if you've got something to show.

Thank you
